version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: findLandRoute-app
    restart: always
    working_dir: /var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: findLandRoute-app-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
